### ISSUE TITLE
docs needed: how to use this repo

### ISSUE THREAD

**Issue by barabo** [microsoft-healthcare-madison/infrastructure#1]
I discovered this repo while searching for how I might configure my local `kubectl` cli to connect to the madison healthcare kubernetes cluster (hopefully I found the right place), and I realized that I don't know enough about how to use this repo to make it work.

I'm thinking we should have a Windows, Linux, and OSX setup page in the Wiki, and I'd be happy to write up an initial draft once I figure out how to make it work.

**Comment by GinoCanessa** [comment]
I've posted a pass in the Wiki (had written it up this morning, but hadn't gotten around to posting).  Please feel free to update as necessary.
